language: ruby
install:
- gem install bundler
- bundle install
branches:
  only:
  - update
script:
- bundle exec jekyll build
- ./deploy.sh
notifications:
  email: false
env:
  matrix:
    secure: Lv2xFwyaqIL1TRTXZar5yYdbGk/VUPdwEYoM2oNEvtzTbn1fthQ+ZkqlODDr40vcWDt5xHDXjNRQZGpdqppcgntiwipadNbUdjML+OYhWaNKXikK2FX3RESfC5hNCnyyx38EFcHkubyjInjy07QcXoH+BVBQaOIBxs8yuKSFzYydtu9z3R9ctWsiOv61gwpjWibIoC4DlVpKicF6mWjoVzhx6ZHAjPAAeoTs0peBJ4HQaVJ6T/vbuiIuTgrsqMjNckIeE061VGdh9uSXFwLNuURD0Psh0V6RHJgkbFvoz9ILXrmzjVVgBYwDQyEjRdkLPLmdWJJ7xWl4AhSFfsoNZnZy8loPhAytzu2ilVZxPUoQAUoPUzfND4mzxtLSwVqab+nDx0Pdy8qFqwuuixz3WCFurUckGSEN2pSWuG0FtvnqDJe4EAKrsNZoS7A3IZ4hIZhiWlNJI3MAZJjF/+xso6vrG4JGc/St30qS/kqXVj8lBQWVbehL5JqKTErPolBXOLWjgHVozjo3/+O4nUe4JMM1Ei1O6kuIli9HBd4G2RnyBxbGi0BMV02S9kq2hXiwps2JKgSXw9yUOlnJfzC83NoK5IkEVi4UCrsjp9bgpiyWOeF2/rgZlSqtbE7AbFbsK8sgmhjezr/gcAEnHGSDX4kL99WPDjK1wOYEHoC/UZw=
