name: squaresLab@CMU cite
permalink: /blog/:year/:month/:day/:title

title: squaresLab@CMU
description: "Software QUality in Real and Evolving Systems Lab at Carnegie
Mellon University"
baseurl: ""
url: "https://squareslab.github.io"

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: clegoues
repo: https://github.com/squaresLab/squaresLab.github.io.git
branch: update

# Build settings
markdown: kramdown
permalink: /:categories/:title

colors:  #in hex code if not noted else
  primary: "#DC2624" #"#00b3fe" #"#F70031"
  primary_rgb: "220,38,36" #"0,179,254" #"247,0,49"
  secondary: "#384452" #"#33004D"
  link: "#96302E" #"#384452" #"#428bca"
  link_hover: "#DC2624" #"#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

plugins: ['jekyll/scholar']

# Custom vars
scholar:
  style: bib.csl
  locale: en

  sort_by: year, month
  order: descending
  group_order: descending

  source: ./_bibliography
  bibliography: publications.bib
  bibliography_template: bib

  bibliography_list_tag: 'div'
  bibliography_item_tag: 'span'

  bibliography_list_attributes:
    reversed: "reversed"

  replace_strings: true
  join_strings:    true

  bibtex_skip_fields: [code, data, tool, results]

  repository: materials

  #details_dir:    bibliography
  #details_layout: bibtex.html
  #details_link:   Details

  query: "@*"

#safe: false
#lsi: false
#pygments: true

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
